name: Bookverse-Backend

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: bookversebackend
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./Bookverse/Bookverse.sln
        
      - name: Build
        run: dotnet build ./Bookverse/Bookverse.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./Bookverse/Bookverse.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.BOOKVERSE_BACKEND_APP }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
